services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    IndyDevGuy\WikiBundle\Repository\WikiEventRepository:
        arguments: ['@doctrine']
        tags: ['doctrine.repository_service']

    IndyDevGuy\WikiBundle\Repository\WikiPageRepository:
        arguments: ['@doctrine']
        tags: ['doctrine.repository_service']

    IndyDevGuy\WikiBundle\Repository\WikiRepository:
        arguments: ['@doctrine']
        tags: ['doctrine.repository_service']

    IndyDevGuy\WikiBundle\Form\WikiPageType:
        arguments: ['@IndyDevGuy\WikiBundle\Repository\WikiPageRepository']
        public: false
        tags:
            - { name: form.type, alias: IndyDevGuy\WikiBundle\Form\WikiPageType }

    IndyDevGuy\WikiBundle\Form\WikiType:
        arguments: ['@IndyDevGuy\WikiBundle\Repository\WikiRepository']
        public: false
        tags:
            - { name: form.type, alias: IndyDevGuy\WikiBundle\Form\WikiType }

    IndyDevGuy\WikiBundle\Services\WikiEventService:
        arguments:
            - '@security.token_storage'
            - '@doctrine.orm.default_entity_manager'
            - '@IndyDevGuy\WikiBundle\Repository\WikiEventRepository'

    IndyDevGuy\WikiBundle\EventListener\ControllerListener:
        arguments: [ '@twig', '@service_container' ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    markdown.engine:
        class: IndyDevGuy\WikiBundle\Twig\Extension\MarkdownEngine\PHPLeagueCommonMarkEngine
    twig.markdown:
        class: Aptoma\Twig\Extension\MarkdownExtension
        arguments: ['@markdown.engine']
        tags:
            - { name: twig.extension }
